version: 2
updates:
  - package-ecosystem: nuget
    directories:
      - "/src/GitHubProfileAnalytics"
      - "/src/Tests/GitHubProfileAnalytics.Tests"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
